#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 5014
EXPOSE 5004

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["nuget.config", "."]
COPY ["src/TicketManagement.UserAPI/TicketManagement.UserAPI.csproj", "src/TicketManagement.UserAPI/"]
COPY ["src/TicketManagement.Common/TicketManagement.Common.csproj", "src/TicketManagement.Common/"]
RUN dotnet restore "src/TicketManagement.UserAPI/TicketManagement.UserAPI.csproj"
COPY . .
WORKDIR "/src/src/TicketManagement.UserAPI"
RUN dotnet build "TicketManagement.UserAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TicketManagement.UserAPI.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TicketManagement.UserAPI.dll"]