#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 7114
EXPOSE 7115

ENV ASPNETCORE_ENVIRONMENT="Development"

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["src/TicketManagement.WebUI/TicketManagement.WebUI.csproj", "src/TicketManagement.WebUI/"]
COPY ["src/TicketManagement.Common/TicketManagement.Common.csproj", "src/TicketManagement.Common/"]
RUN dotnet restore "src/TicketManagement.WebUI/TicketManagement.WebUI.csproj"
COPY . .
WORKDIR "/src/src/TicketManagement.WebUI"
RUN dotnet build "TicketManagement.WebUI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TicketManagement.WebUI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TicketManagement.WebUI.dll"]
